version: "3.4"

services:
  mysql:
    image: library/mysql:5.7
    entrypoint: ['/entrypoint.sh', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    user: mysql
    environment:
      - MYSQL_DATABASE=secret_santa
      - MYSQL_USER=secret_santa
      - MYSQL_PASSWORD=secret_santa
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Berlin
    ports:
      - "3306:3306"

