// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package secretsanta_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	date "google.golang.org/genproto/googleapis/type/date"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupStatus int32

const (
	GroupStatus_UNDEFINED_GROUP_STATUS GroupStatus = 0
	GroupStatus_CREATED_GROUP_STATUS   GroupStatus = 1
	GroupStatus_INVITED_GROUP_STATUS   GroupStatus = 2
	GroupStatus_MAPPED_GROUP_STATUS    GroupStatus = 3
	GroupStatus_FINISHED_GROUP_STATUS  GroupStatus = 4
)

var GroupStatus_name = map[int32]string{
	0: "UNDEFINED_GROUP_STATUS",
	1: "CREATED_GROUP_STATUS",
	2: "INVITED_GROUP_STATUS",
	3: "MAPPED_GROUP_STATUS",
	4: "FINISHED_GROUP_STATUS",
}

var GroupStatus_value = map[string]int32{
	"UNDEFINED_GROUP_STATUS": 0,
	"CREATED_GROUP_STATUS":   1,
	"INVITED_GROUP_STATUS":   2,
	"MAPPED_GROUP_STATUS":    3,
	"FINISHED_GROUP_STATUS":  4,
}

func (x GroupStatus) String() string {
	return proto.EnumName(GroupStatus_name, int32(x))
}

func (GroupStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

type Group struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatorName          string         `protobuf:"bytes,3,opt,name=creatorName,proto3" json:"creatorName,omitempty"`
	Members              []*GroupMember `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	CreatedAt            *date.Date     `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetCreatorName() string {
	if m != nil {
		return m.CreatorName
	}
	return ""
}

func (m *Group) GetMembers() []*GroupMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Group) GetCreatedAt() *date.Date {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type GroupMember struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMember) Reset()         { *m = GroupMember{} }
func (m *GroupMember) String() string { return proto.CompactTextString(m) }
func (*GroupMember) ProtoMessage()    {}
func (*GroupMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *GroupMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMember.Unmarshal(m, b)
}
func (m *GroupMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMember.Marshal(b, m, deterministic)
}
func (m *GroupMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMember.Merge(m, src)
}
func (m *GroupMember) XXX_Size() int {
	return xxx_messageInfo_GroupMember.Size(m)
}
func (m *GroupMember) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMember.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMember proto.InternalMessageInfo

func (m *GroupMember) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GroupMember) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Wish struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Note                 string   `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wish) Reset()         { *m = Wish{} }
func (m *Wish) String() string { return proto.CompactTextString(m) }
func (*Wish) ProtoMessage()    {}
func (*Wish) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *Wish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wish.Unmarshal(m, b)
}
func (m *Wish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wish.Marshal(b, m, deterministic)
}
func (m *Wish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wish.Merge(m, src)
}
func (m *Wish) XXX_Size() int {
	return xxx_messageInfo_Wish.Size(m)
}
func (m *Wish) XXX_DiscardUnknown() {
	xxx_messageInfo_Wish.DiscardUnknown(m)
}

var xxx_messageInfo_Wish proto.InternalMessageInfo

func (m *Wish) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Wish) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Wish) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func init() {
	proto.RegisterEnum("secretsanta.v1.GroupStatus", GroupStatus_name, GroupStatus_value)
	proto.RegisterType((*Group)(nil), "secretsanta.v1.Group")
	proto.RegisterType((*GroupMember)(nil), "secretsanta.v1.GroupMember")
	proto.RegisterType((*Wish)(nil), "secretsanta.v1.Wish")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x6d, 0x29, 0x1a, 0xa6, 0x09, 0xd1, 0xf1, 0xaf, 0xe2, 0xa6, 0xe9, 0x8a, 0xb8, 0x98,
	0x06, 0x8c, 0x5b, 0x93, 0x46, 0x7e, 0xec, 0x82, 0x4a, 0x5a, 0xd0, 0x25, 0x19, 0xe8, 0x0d, 0x34,
	0xb1, 0x4c, 0x33, 0x73, 0x31, 0xe1, 0x31, 0x7c, 0x18, 0xdf, 0xcf, 0x74, 0x90, 0x88, 0xb8, 0x61,
	0x77, 0x73, 0xbe, 0x33, 0xf7, 0x9e, 0x93, 0x21, 0xf5, 0x1c, 0x94, 0xe2, 0x73, 0x50, 0xac, 0x90,
	0x02, 0x05, 0xad, 0x2b, 0x98, 0x49, 0x40, 0xc5, 0x97, 0xc8, 0xd9, 0x47, 0xab, 0xe1, 0xe1, 0x22,
	0x93, 0xe9, 0xa4, 0xe0, 0x12, 0xd7, 0xfe, 0x5c, 0x88, 0xf9, 0x3b, 0xf8, 0xb8, 0x2e, 0xc0, 0x4f,
	0x39, 0xc2, 0xe6, 0x8d, 0xf7, 0x65, 0x90, 0x6a, 0x5f, 0x8a, 0x55, 0x41, 0xeb, 0xc4, 0xcc, 0x52,
	0xc7, 0x70, 0x8d, 0x66, 0x2d, 0x36, 0xb3, 0x94, 0x52, 0x62, 0x2d, 0x79, 0x0e, 0x8e, 0xa9, 0x15,
	0x3d, 0x53, 0x97, 0xd8, 0x33, 0x09, 0x1c, 0x85, 0x8c, 0x4a, 0x54, 0xd1, 0x68, 0x57, 0xa2, 0x0f,
	0xe4, 0x24, 0x87, 0x7c, 0x0a, 0x52, 0x39, 0x96, 0x5b, 0x69, 0xda, 0xed, 0x5b, 0xf6, 0x37, 0x15,
	0xd3, 0xd7, 0x06, 0xda, 0x13, 0x6f, 0xbd, 0xd4, 0x27, 0x35, 0xbd, 0x05, 0xd2, 0x00, 0x9d, 0xaa,
	0x6b, 0x34, 0xed, 0xf6, 0x19, 0xdb, 0x44, 0x66, 0x65, 0x64, 0xd6, 0xe1, 0x08, 0xf1, 0xaf, 0xc7,
	0x6b, 0x11, 0x7b, 0x67, 0xd1, 0x21, 0xe1, 0xbd, 0x47, 0x62, 0xbd, 0x65, 0x6a, 0x71, 0x50, 0xd1,
	0x52, 0x13, 0xb8, 0x6d, 0xa8, 0xe7, 0xbb, 0x4f, 0xe3, 0xe7, 0x66, 0x82, 0x1c, 0x57, 0x8a, 0x36,
	0xc8, 0xd5, 0x38, 0xea, 0x74, 0x7b, 0x61, 0xd4, 0xed, 0x4c, 0xfa, 0xf1, 0xcb, 0x78, 0x38, 0x49,
	0x46, 0xc1, 0x68, 0x9c, 0x9c, 0x1e, 0x51, 0x87, 0x5c, 0x3c, 0xc5, 0xdd, 0x60, 0xb4, 0x4f, 0x8c,
	0x92, 0x84, 0xd1, 0x6b, 0xf8, 0x8f, 0x98, 0xf4, 0x9a, 0x9c, 0x0f, 0x82, 0xe1, 0x70, 0x1f, 0x54,
	0xe8, 0x0d, 0xb9, 0xec, 0x85, 0x51, 0x98, 0x3c, 0xef, 0x23, 0x6b, 0x7a, 0xac, 0x7f, 0xf1, 0xfe,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0xab, 0xe6, 0x76, 0xe0, 0x0b, 0x02, 0x00, 0x00,
}
