// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package secretsanta_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateGroupRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatorName          string   `protobuf:"bytes,2,opt,name=creatorName,proto3" json:"creatorName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(m, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateGroupRequest) GetCreatorName() string {
	if m != nil {
		return m.CreatorName
	}
	return ""
}

type CreateGroupResponse struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupResponse) Reset()         { *m = CreateGroupResponse{} }
func (m *CreateGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGroupResponse) ProtoMessage()    {}
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *CreateGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupResponse.Unmarshal(m, b)
}
func (m *CreateGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupResponse.Marshal(b, m, deterministic)
}
func (m *CreateGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupResponse.Merge(m, src)
}
func (m *CreateGroupResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGroupResponse.Size(m)
}
func (m *CreateGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupResponse proto.InternalMessageInfo

func (m *CreateGroupResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GetGroupRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupRequest) Reset()         { *m = GetGroupRequest{} }
func (m *GetGroupRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupRequest) ProtoMessage()    {}
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *GetGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupRequest.Unmarshal(m, b)
}
func (m *GetGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupRequest.Merge(m, src)
}
func (m *GetGroupRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupRequest.Size(m)
}
func (m *GetGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupRequest proto.InternalMessageInfo

func (m *GetGroupRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type GetGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupResponse) Reset()         { *m = GetGroupResponse{} }
func (m *GetGroupResponse) String() string { return proto.CompactTextString(m) }
func (*GetGroupResponse) ProtoMessage()    {}
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GetGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupResponse.Unmarshal(m, b)
}
func (m *GetGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupResponse.Marshal(b, m, deterministic)
}
func (m *GetGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupResponse.Merge(m, src)
}
func (m *GetGroupResponse) XXX_Size() int {
	return xxx_messageInfo_GetGroupResponse.Size(m)
}
func (m *GetGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupResponse proto.InternalMessageInfo

type AddGroupMemberRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupMemberRequest) Reset()         { *m = AddGroupMemberRequest{} }
func (m *AddGroupMemberRequest) String() string { return proto.CompactTextString(m) }
func (*AddGroupMemberRequest) ProtoMessage()    {}
func (*AddGroupMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *AddGroupMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupMemberRequest.Unmarshal(m, b)
}
func (m *AddGroupMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupMemberRequest.Marshal(b, m, deterministic)
}
func (m *AddGroupMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupMemberRequest.Merge(m, src)
}
func (m *AddGroupMemberRequest) XXX_Size() int {
	return xxx_messageInfo_AddGroupMemberRequest.Size(m)
}
func (m *AddGroupMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupMemberRequest proto.InternalMessageInfo

func (m *AddGroupMemberRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *AddGroupMemberRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddGroupMemberRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AddGroupMemberResponse struct {
	Member               *GroupMember `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddGroupMemberResponse) Reset()         { *m = AddGroupMemberResponse{} }
func (m *AddGroupMemberResponse) String() string { return proto.CompactTextString(m) }
func (*AddGroupMemberResponse) ProtoMessage()    {}
func (*AddGroupMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *AddGroupMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupMemberResponse.Unmarshal(m, b)
}
func (m *AddGroupMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupMemberResponse.Marshal(b, m, deterministic)
}
func (m *AddGroupMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupMemberResponse.Merge(m, src)
}
func (m *AddGroupMemberResponse) XXX_Size() int {
	return xxx_messageInfo_AddGroupMemberResponse.Size(m)
}
func (m *AddGroupMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupMemberResponse proto.InternalMessageInfo

func (m *AddGroupMemberResponse) GetMember() *GroupMember {
	if m != nil {
		return m.Member
	}
	return nil
}

type SendInviteEmailsRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendInviteEmailsRequest) Reset()         { *m = SendInviteEmailsRequest{} }
func (m *SendInviteEmailsRequest) String() string { return proto.CompactTextString(m) }
func (*SendInviteEmailsRequest) ProtoMessage()    {}
func (*SendInviteEmailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *SendInviteEmailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendInviteEmailsRequest.Unmarshal(m, b)
}
func (m *SendInviteEmailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendInviteEmailsRequest.Marshal(b, m, deterministic)
}
func (m *SendInviteEmailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendInviteEmailsRequest.Merge(m, src)
}
func (m *SendInviteEmailsRequest) XXX_Size() int {
	return xxx_messageInfo_SendInviteEmailsRequest.Size(m)
}
func (m *SendInviteEmailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendInviteEmailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendInviteEmailsRequest proto.InternalMessageInfo

func (m *SendInviteEmailsRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type SendInviteEmailsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendInviteEmailsResponse) Reset()         { *m = SendInviteEmailsResponse{} }
func (m *SendInviteEmailsResponse) String() string { return proto.CompactTextString(m) }
func (*SendInviteEmailsResponse) ProtoMessage()    {}
func (*SendInviteEmailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *SendInviteEmailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendInviteEmailsResponse.Unmarshal(m, b)
}
func (m *SendInviteEmailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendInviteEmailsResponse.Marshal(b, m, deterministic)
}
func (m *SendInviteEmailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendInviteEmailsResponse.Merge(m, src)
}
func (m *SendInviteEmailsResponse) XXX_Size() int {
	return xxx_messageInfo_SendInviteEmailsResponse.Size(m)
}
func (m *SendInviteEmailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendInviteEmailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendInviteEmailsResponse proto.InternalMessageInfo

type SaveWishesRequest struct {
	MemberId             string   `protobuf:"bytes,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	Wishes               []*Wish  `protobuf:"bytes,2,rep,name=wishes,proto3" json:"wishes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveWishesRequest) Reset()         { *m = SaveWishesRequest{} }
func (m *SaveWishesRequest) String() string { return proto.CompactTextString(m) }
func (*SaveWishesRequest) ProtoMessage()    {}
func (*SaveWishesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *SaveWishesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveWishesRequest.Unmarshal(m, b)
}
func (m *SaveWishesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveWishesRequest.Marshal(b, m, deterministic)
}
func (m *SaveWishesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveWishesRequest.Merge(m, src)
}
func (m *SaveWishesRequest) XXX_Size() int {
	return xxx_messageInfo_SaveWishesRequest.Size(m)
}
func (m *SaveWishesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveWishesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveWishesRequest proto.InternalMessageInfo

func (m *SaveWishesRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *SaveWishesRequest) GetWishes() []*Wish {
	if m != nil {
		return m.Wishes
	}
	return nil
}

type SaveWishesResponse struct {
	Member               *GroupMember `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SaveWishesResponse) Reset()         { *m = SaveWishesResponse{} }
func (m *SaveWishesResponse) String() string { return proto.CompactTextString(m) }
func (*SaveWishesResponse) ProtoMessage()    {}
func (*SaveWishesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *SaveWishesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveWishesResponse.Unmarshal(m, b)
}
func (m *SaveWishesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveWishesResponse.Marshal(b, m, deterministic)
}
func (m *SaveWishesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveWishesResponse.Merge(m, src)
}
func (m *SaveWishesResponse) XXX_Size() int {
	return xxx_messageInfo_SaveWishesResponse.Size(m)
}
func (m *SaveWishesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveWishesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveWishesResponse proto.InternalMessageInfo

func (m *SaveWishesResponse) GetMember() *GroupMember {
	if m != nil {
		return m.Member
	}
	return nil
}

type CreateMappingRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMappingRequest) Reset()         { *m = CreateMappingRequest{} }
func (m *CreateMappingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMappingRequest) ProtoMessage()    {}
func (*CreateMappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *CreateMappingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMappingRequest.Unmarshal(m, b)
}
func (m *CreateMappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMappingRequest.Marshal(b, m, deterministic)
}
func (m *CreateMappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMappingRequest.Merge(m, src)
}
func (m *CreateMappingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMappingRequest.Size(m)
}
func (m *CreateMappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMappingRequest proto.InternalMessageInfo

func (m *CreateMappingRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type CreateMappingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMappingResponse) Reset()         { *m = CreateMappingResponse{} }
func (m *CreateMappingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMappingResponse) ProtoMessage()    {}
func (*CreateMappingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *CreateMappingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMappingResponse.Unmarshal(m, b)
}
func (m *CreateMappingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMappingResponse.Marshal(b, m, deterministic)
}
func (m *CreateMappingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMappingResponse.Merge(m, src)
}
func (m *CreateMappingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMappingResponse.Size(m)
}
func (m *CreateMappingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMappingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMappingResponse proto.InternalMessageInfo

type SendSantaEmailsRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSantaEmailsRequest) Reset()         { *m = SendSantaEmailsRequest{} }
func (m *SendSantaEmailsRequest) String() string { return proto.CompactTextString(m) }
func (*SendSantaEmailsRequest) ProtoMessage()    {}
func (*SendSantaEmailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *SendSantaEmailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSantaEmailsRequest.Unmarshal(m, b)
}
func (m *SendSantaEmailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSantaEmailsRequest.Marshal(b, m, deterministic)
}
func (m *SendSantaEmailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSantaEmailsRequest.Merge(m, src)
}
func (m *SendSantaEmailsRequest) XXX_Size() int {
	return xxx_messageInfo_SendSantaEmailsRequest.Size(m)
}
func (m *SendSantaEmailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSantaEmailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendSantaEmailsRequest proto.InternalMessageInfo

func (m *SendSantaEmailsRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type SendSantaEmailsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSantaEmailsResponse) Reset()         { *m = SendSantaEmailsResponse{} }
func (m *SendSantaEmailsResponse) String() string { return proto.CompactTextString(m) }
func (*SendSantaEmailsResponse) ProtoMessage()    {}
func (*SendSantaEmailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *SendSantaEmailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSantaEmailsResponse.Unmarshal(m, b)
}
func (m *SendSantaEmailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSantaEmailsResponse.Marshal(b, m, deterministic)
}
func (m *SendSantaEmailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSantaEmailsResponse.Merge(m, src)
}
func (m *SendSantaEmailsResponse) XXX_Size() int {
	return xxx_messageInfo_SendSantaEmailsResponse.Size(m)
}
func (m *SendSantaEmailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSantaEmailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendSantaEmailsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateGroupRequest)(nil), "secretsanta.v1.CreateGroupRequest")
	proto.RegisterType((*CreateGroupResponse)(nil), "secretsanta.v1.CreateGroupResponse")
	proto.RegisterType((*GetGroupRequest)(nil), "secretsanta.v1.GetGroupRequest")
	proto.RegisterType((*GetGroupResponse)(nil), "secretsanta.v1.GetGroupResponse")
	proto.RegisterType((*AddGroupMemberRequest)(nil), "secretsanta.v1.AddGroupMemberRequest")
	proto.RegisterType((*AddGroupMemberResponse)(nil), "secretsanta.v1.AddGroupMemberResponse")
	proto.RegisterType((*SendInviteEmailsRequest)(nil), "secretsanta.v1.SendInviteEmailsRequest")
	proto.RegisterType((*SendInviteEmailsResponse)(nil), "secretsanta.v1.SendInviteEmailsResponse")
	proto.RegisterType((*SaveWishesRequest)(nil), "secretsanta.v1.SaveWishesRequest")
	proto.RegisterType((*SaveWishesResponse)(nil), "secretsanta.v1.SaveWishesResponse")
	proto.RegisterType((*CreateMappingRequest)(nil), "secretsanta.v1.CreateMappingRequest")
	proto.RegisterType((*CreateMappingResponse)(nil), "secretsanta.v1.CreateMappingResponse")
	proto.RegisterType((*SendSantaEmailsRequest)(nil), "secretsanta.v1.SendSantaEmailsRequest")
	proto.RegisterType((*SendSantaEmailsResponse)(nil), "secretsanta.v1.SendSantaEmailsResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 668 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5b, 0x4f, 0x13, 0x41,
	0x14, 0xce, 0x16, 0xb9, 0x9d, 0x86, 0x82, 0x43, 0x0b, 0xcb, 0x80, 0x52, 0x86, 0x5b, 0x03, 0xd2,
	0xa5, 0xed, 0x8b, 0xf1, 0xad, 0x18, 0x43, 0x6a, 0x52, 0x43, 0xda, 0x07, 0x1f, 0x8c, 0x31, 0x43,
	0x3b, 0x59, 0xd6, 0x74, 0x2f, 0xee, 0x2c, 0x25, 0x06, 0x89, 0xd1, 0x67, 0xf5, 0x41, 0x7f, 0x9a,
	0x7f, 0xc1, 0x1f, 0x62, 0x66, 0x76, 0x5a, 0xba, 0x17, 0x58, 0x13, 0xdf, 0xba, 0x73, 0xbe, 0xf3,
	0x5d, 0x4e, 0xce, 0x49, 0x61, 0x81, 0x33, 0x7f, 0x68, 0xf5, 0x58, 0xd5, 0xf3, 0xdd, 0xc0, 0x45,
	0x05, 0xce, 0x7a, 0x3e, 0x0b, 0x38, 0x75, 0x02, 0x5a, 0x1d, 0xd6, 0x70, 0xc1, 0x66, 0x9c, 0x53,
	0x93, 0xf1, 0xb0, 0x8e, 0x2b, 0xc1, 0x85, 0xe5, 0xf7, 0xdf, 0x79, 0xd4, 0x0f, 0x3e, 0x1a, 0xa6,
	0xeb, 0x9a, 0x03, 0x66, 0x50, 0xcf, 0x32, 0xa8, 0xe3, 0xb8, 0x01, 0x0d, 0x2c, 0xd7, 0x19, 0x21,
	0x9f, 0x4e, 0x22, 0xe5, 0x53, 0xef, 0xc8, 0x64, 0xce, 0x11, 0xbf, 0xa2, 0xa6, 0xc9, 0x7c, 0xc3,
	0xf5, 0x24, 0x3a, 0xd9, 0x49, 0x5e, 0x02, 0x7a, 0xee, 0x33, 0x1a, 0xb0, 0x53, 0xdf, 0xbd, 0xf4,
	0x3a, 0xec, 0xc3, 0x25, 0xe3, 0x01, 0x42, 0xf0, 0xc0, 0xa1, 0x36, 0xd3, 0xb5, 0xb2, 0x56, 0x99,
	0xef, 0xc8, 0xdf, 0xa8, 0x0c, 0xf9, 0x9e, 0x40, 0xba, 0xfe, 0x2b, 0x51, 0xca, 0xc9, 0xd2, 0xe4,
	0x13, 0x39, 0x81, 0xe5, 0x08, 0x17, 0xf7, 0x5c, 0x87, 0x33, 0x74, 0x08, 0xd3, 0xa6, 0x78, 0x90,
	0x6c, 0xf9, 0x7a, 0xa9, 0x1a, 0x8d, 0x5d, 0x0d, 0xd1, 0x21, 0x86, 0x1c, 0xc2, 0xe2, 0x29, 0x0b,
	0x22, 0x66, 0x74, 0x98, 0x95, 0xb5, 0x56, 0x5f, 0xf9, 0x19, 0x7d, 0x12, 0x04, 0x4b, 0xb7, 0xe0,
	0x50, 0x8d, 0xbc, 0x81, 0x52, 0xb3, 0xdf, 0x97, 0x6f, 0x6d, 0x66, 0x9f, 0x33, 0x3f, 0x93, 0x66,
	0x9c, 0x36, 0x37, 0x91, 0xb6, 0x08, 0xd3, 0xcc, 0xa6, 0xd6, 0x40, 0x9f, 0x92, 0x8f, 0xe1, 0x07,
	0x69, 0xc3, 0x4a, 0x9c, 0x5c, 0x85, 0x6c, 0xc0, 0x8c, 0x2d, 0x5f, 0x54, 0xca, 0xf5, 0xd4, 0x94,
	0xaa, 0x49, 0x41, 0x49, 0x03, 0x56, 0xbb, 0xcc, 0xe9, 0xb7, 0x9c, 0xa1, 0x15, 0xb0, 0x17, 0x42,
	0x81, 0x67, 0x87, 0xc6, 0xa0, 0x27, 0x9b, 0x54, 0xf8, 0xb7, 0xf0, 0xb0, 0x4b, 0x87, 0xec, 0xb5,
	0xc5, 0x2f, 0xd8, 0x98, 0x0a, 0xc3, 0x5c, 0xa8, 0x37, 0xe6, 0x1a, 0x7f, 0xa3, 0x27, 0x30, 0x73,
	0x25, 0xc1, 0x7a, 0xae, 0x3c, 0x55, 0xc9, 0xd7, 0x8b, 0x71, 0xdb, 0x82, 0xaa, 0xa3, 0x30, 0xa4,
	0x05, 0x68, 0x92, 0xfe, 0x7f, 0xa2, 0x1f, 0x43, 0x31, 0xdc, 0x95, 0x36, 0xf5, 0x3c, 0xcb, 0x31,
	0xb3, 0x73, 0xaf, 0x42, 0x29, 0xd6, 0xa1, 0x42, 0xd7, 0x61, 0x45, 0x0c, 0xa4, 0x2b, 0xe4, 0xfe,
	0x75, 0x88, 0x6b, 0xe1, 0xe4, 0x23, 0x3d, 0x21, 0x5d, 0xfd, 0xfb, 0x2c, 0x14, 0xba, 0x32, 0x80,
	0xac, 0x36, 0xcf, 0x5a, 0x68, 0x00, 0xf9, 0x89, 0xc5, 0x46, 0x24, 0x1e, 0x30, 0x79, 0x41, 0x78,
	0xfb, 0x5e, 0x8c, 0x72, 0x5e, 0xfc, 0xfa, 0xfb, 0xcf, 0xaf, 0x5c, 0x81, 0xcc, 0x1b, 0xc3, 0x9a,
	0x21, 0xad, 0x3d, 0xd3, 0x0e, 0xd0, 0x7b, 0x98, 0x1b, 0x6d, 0x35, 0xda, 0x4c, 0xcc, 0x32, 0x7a,
	0x1c, 0xb8, 0x7c, 0x37, 0x40, 0x89, 0xac, 0x4b, 0x91, 0x12, 0x5a, 0x1e, 0x8b, 0x18, 0xd7, 0x6a,
	0x0c, 0x37, 0xe8, 0x33, 0x14, 0xa2, 0x0b, 0x8d, 0x76, 0xe3, 0x84, 0xa9, 0xd7, 0x84, 0xf7, 0xb2,
	0x60, 0x4a, 0xfd, 0xb1, 0x54, 0xd7, 0x49, 0x9a, 0xba, 0x08, 0xfb, 0x4d, 0x83, 0xa5, 0xf8, 0x3a,
	0xa3, 0xfd, 0x38, 0xf9, 0x1d, 0x57, 0x82, 0x2b, 0xd9, 0x40, 0xe5, 0x63, 0x57, 0xfa, 0xd8, 0x24,
	0x38, 0xc5, 0x87, 0x61, 0xc9, 0x0e, 0x61, 0xe7, 0x13, 0xc0, 0xed, 0x86, 0xa3, 0xad, 0x04, 0x7d,
	0xfc, 0xb8, 0x30, 0xb9, 0x0f, 0xa2, 0xb4, 0xf7, 0xa5, 0xf6, 0x16, 0xd9, 0x10, 0xda, 0xe1, 0xfe,
	0x1b, 0xd7, 0xa3, 0x13, 0xbc, 0x31, 0xc2, 0xe3, 0x12, 0xea, 0x5f, 0x34, 0x58, 0x88, 0xec, 0x38,
	0xda, 0x49, 0x5f, 0xa3, 0xe8, 0xd1, 0xe0, 0xdd, 0x0c, 0x94, 0xf2, 0xb1, 0x2d, 0x7d, 0x3c, 0x22,
	0xeb, 0x69, 0x33, 0xb0, 0x95, 0xe2, 0x0f, 0x0d, 0x16, 0x63, 0xa7, 0x81, 0xf6, 0xd2, 0xc6, 0x9c,
	0xbc, 0x37, 0xbc, 0x9f, 0x89, 0x53, 0x4e, 0x0e, 0xa4, 0x93, 0x1d, 0x42, 0xd2, 0x9c, 0xf0, 0x51,
	0x53, 0x5b, 0xf4, 0x9c, 0x6c, 0xfc, 0x6c, 0xae, 0xa1, 0x55, 0xb1, 0x25, 0x82, 0xfa, 0x48, 0x56,
	0xca, 0xcd, 0xb3, 0x56, 0x7d, 0xaa, 0x56, 0x3d, 0x3e, 0x9f, 0x91, 0x7f, 0x63, 0x8d, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x6e, 0xb3, 0xe6, 0x08, 0x5b, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecretSantaAPIClient is the client API for SecretSantaAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecretSantaAPIClient interface {
	// CreateGroup stores a new group.
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error)
	// Add a group member to a given group.
	AddGroupMember(ctx context.Context, in *AddGroupMemberRequest, opts ...grpc.CallOption) (*AddGroupMemberResponse, error)
	// Send invite emails to all group members. Does not return anything.
	SendInviteEmails(ctx context.Context, in *SendInviteEmailsRequest, opts ...grpc.CallOption) (*SendInviteEmailsResponse, error)
	// Save multiple wishes for a given GroupMember.
	// Wishes can only be saved as long as no 'santa-mapping' has been created.
	SaveWishes(ctx context.Context, in *SaveWishesRequest, opts ...grpc.CallOption) (*SaveWishesResponse, error)
	// Creates a secret-santa mapping permutation and stores it in the database.
	// Does not return anything, only fails if something went wrong.
	// A mapping can only be created if all group members have saved their wish-lists.
	// Creating a mapping will 'close' the group and prevent any further changes of members wishes.
	CreateMapping(ctx context.Context, in *CreateMappingRequest, opts ...grpc.CallOption) (*CreateMappingResponse, error)
	// Sends out emails to all members containing the information about their special one :)
	// This RPC will fail if no mapping has been created. Does not return anything.
	SendSantaEmails(ctx context.Context, in *SendSantaEmailsRequest, opts ...grpc.CallOption) (*SendSantaEmailsResponse, error)
}

type secretSantaAPIClient struct {
	cc *grpc.ClientConn
}

func NewSecretSantaAPIClient(cc *grpc.ClientConn) SecretSantaAPIClient {
	return &secretSantaAPIClient{cc}
}

func (c *secretSantaAPIClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, "/secretsanta.v1.SecretSantaAPI/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretSantaAPIClient) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error) {
	out := new(GetGroupResponse)
	err := c.cc.Invoke(ctx, "/secretsanta.v1.SecretSantaAPI/GetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretSantaAPIClient) AddGroupMember(ctx context.Context, in *AddGroupMemberRequest, opts ...grpc.CallOption) (*AddGroupMemberResponse, error) {
	out := new(AddGroupMemberResponse)
	err := c.cc.Invoke(ctx, "/secretsanta.v1.SecretSantaAPI/AddGroupMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretSantaAPIClient) SendInviteEmails(ctx context.Context, in *SendInviteEmailsRequest, opts ...grpc.CallOption) (*SendInviteEmailsResponse, error) {
	out := new(SendInviteEmailsResponse)
	err := c.cc.Invoke(ctx, "/secretsanta.v1.SecretSantaAPI/SendInviteEmails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretSantaAPIClient) SaveWishes(ctx context.Context, in *SaveWishesRequest, opts ...grpc.CallOption) (*SaveWishesResponse, error) {
	out := new(SaveWishesResponse)
	err := c.cc.Invoke(ctx, "/secretsanta.v1.SecretSantaAPI/SaveWishes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretSantaAPIClient) CreateMapping(ctx context.Context, in *CreateMappingRequest, opts ...grpc.CallOption) (*CreateMappingResponse, error) {
	out := new(CreateMappingResponse)
	err := c.cc.Invoke(ctx, "/secretsanta.v1.SecretSantaAPI/CreateMapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretSantaAPIClient) SendSantaEmails(ctx context.Context, in *SendSantaEmailsRequest, opts ...grpc.CallOption) (*SendSantaEmailsResponse, error) {
	out := new(SendSantaEmailsResponse)
	err := c.cc.Invoke(ctx, "/secretsanta.v1.SecretSantaAPI/SendSantaEmails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretSantaAPIServer is the server API for SecretSantaAPI service.
type SecretSantaAPIServer interface {
	// CreateGroup stores a new group.
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	GetGroup(context.Context, *GetGroupRequest) (*GetGroupResponse, error)
	// Add a group member to a given group.
	AddGroupMember(context.Context, *AddGroupMemberRequest) (*AddGroupMemberResponse, error)
	// Send invite emails to all group members. Does not return anything.
	SendInviteEmails(context.Context, *SendInviteEmailsRequest) (*SendInviteEmailsResponse, error)
	// Save multiple wishes for a given GroupMember.
	// Wishes can only be saved as long as no 'santa-mapping' has been created.
	SaveWishes(context.Context, *SaveWishesRequest) (*SaveWishesResponse, error)
	// Creates a secret-santa mapping permutation and stores it in the database.
	// Does not return anything, only fails if something went wrong.
	// A mapping can only be created if all group members have saved their wish-lists.
	// Creating a mapping will 'close' the group and prevent any further changes of members wishes.
	CreateMapping(context.Context, *CreateMappingRequest) (*CreateMappingResponse, error)
	// Sends out emails to all members containing the information about their special one :)
	// This RPC will fail if no mapping has been created. Does not return anything.
	SendSantaEmails(context.Context, *SendSantaEmailsRequest) (*SendSantaEmailsResponse, error)
}

// UnimplementedSecretSantaAPIServer can be embedded to have forward compatible implementations.
type UnimplementedSecretSantaAPIServer struct {
}

func (*UnimplementedSecretSantaAPIServer) CreateGroup(ctx context.Context, req *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedSecretSantaAPIServer) GetGroup(ctx context.Context, req *GetGroupRequest) (*GetGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (*UnimplementedSecretSantaAPIServer) AddGroupMember(ctx context.Context, req *AddGroupMemberRequest) (*AddGroupMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGroupMember not implemented")
}
func (*UnimplementedSecretSantaAPIServer) SendInviteEmails(ctx context.Context, req *SendInviteEmailsRequest) (*SendInviteEmailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInviteEmails not implemented")
}
func (*UnimplementedSecretSantaAPIServer) SaveWishes(ctx context.Context, req *SaveWishesRequest) (*SaveWishesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveWishes not implemented")
}
func (*UnimplementedSecretSantaAPIServer) CreateMapping(ctx context.Context, req *CreateMappingRequest) (*CreateMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMapping not implemented")
}
func (*UnimplementedSecretSantaAPIServer) SendSantaEmails(ctx context.Context, req *SendSantaEmailsRequest) (*SendSantaEmailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSantaEmails not implemented")
}

func RegisterSecretSantaAPIServer(s *grpc.Server, srv SecretSantaAPIServer) {
	s.RegisterService(&_SecretSantaAPI_serviceDesc, srv)
}

func _SecretSantaAPI_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretSantaAPIServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secretsanta.v1.SecretSantaAPI/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretSantaAPIServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretSantaAPI_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretSantaAPIServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secretsanta.v1.SecretSantaAPI/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretSantaAPIServer).GetGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretSantaAPI_AddGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGroupMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretSantaAPIServer).AddGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secretsanta.v1.SecretSantaAPI/AddGroupMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretSantaAPIServer).AddGroupMember(ctx, req.(*AddGroupMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretSantaAPI_SendInviteEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendInviteEmailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretSantaAPIServer).SendInviteEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secretsanta.v1.SecretSantaAPI/SendInviteEmails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretSantaAPIServer).SendInviteEmails(ctx, req.(*SendInviteEmailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretSantaAPI_SaveWishes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveWishesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretSantaAPIServer).SaveWishes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secretsanta.v1.SecretSantaAPI/SaveWishes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretSantaAPIServer).SaveWishes(ctx, req.(*SaveWishesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretSantaAPI_CreateMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretSantaAPIServer).CreateMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secretsanta.v1.SecretSantaAPI/CreateMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretSantaAPIServer).CreateMapping(ctx, req.(*CreateMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretSantaAPI_SendSantaEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSantaEmailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretSantaAPIServer).SendSantaEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secretsanta.v1.SecretSantaAPI/SendSantaEmails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretSantaAPIServer).SendSantaEmails(ctx, req.(*SendSantaEmailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecretSantaAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "secretsanta.v1.SecretSantaAPI",
	HandlerType: (*SecretSantaAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _SecretSantaAPI_CreateGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _SecretSantaAPI_GetGroup_Handler,
		},
		{
			MethodName: "AddGroupMember",
			Handler:    _SecretSantaAPI_AddGroupMember_Handler,
		},
		{
			MethodName: "SendInviteEmails",
			Handler:    _SecretSantaAPI_SendInviteEmails_Handler,
		},
		{
			MethodName: "SaveWishes",
			Handler:    _SecretSantaAPI_SaveWishes_Handler,
		},
		{
			MethodName: "CreateMapping",
			Handler:    _SecretSantaAPI_CreateMapping_Handler,
		},
		{
			MethodName: "SendSantaEmails",
			Handler:    _SecretSantaAPI_SendSantaEmails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
