package actions

import (

  "fmt"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "secret_santa/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Group)
// DB Table: Plural (groups)
// Resource: Plural (Groups)
// Path: Plural (/groups)
// View Template Folder: Plural (/templates/groups/)

// GroupsResource is the resource for the Group model
type GroupsResource struct{
  buffalo.Resource
}

// List gets all Groups. This function is mapped to the path
// GET /groups
func (v GroupsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  groups := &models.Groups{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Groups from the DB
  if err := q.All(groups); err != nil {
    return err
  }

  // Add the paginator to the context so it can be used in the template.
  c.Set("pagination", q.Paginator)

  return c.Render(200, r.Auto(c, groups))
}

// Show gets the data for one Group. This function is mapped to
// the path GET /groups/{group_id}
func (v GroupsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Group
  group := &models.Group{}

  // To find the Group the parameter group_id is used.
  if err := tx.Find(group, c.Param("group_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, group))
}

// New renders the form for creating a new Group.
// This function is mapped to the path GET /groups/new
func (v GroupsResource) New(c buffalo.Context) error {
  return c.Render(200, r.Auto(c, &models.Group{}))
}
// Create adds a Group to the DB. This function is mapped to the
// path POST /groups
func (v GroupsResource) Create(c buffalo.Context) error {
  // Allocate an empty Group
  group := &models.Group{}

  // Bind group to the html form elements
  if err := c.Bind(group); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(group)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the new.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, group))
  }

  // If there are no errors set a success message
  c.Flash().Add("success", T.Translate(c, "group.created.success"))
  // and redirect to the groups index page
  return c.Render(201, r.Auto(c, group))
}

// Edit renders a edit form for a Group. This function is
// mapped to the path GET /groups/{group_id}/edit
func (v GroupsResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Group
  group := &models.Group{}

  if err := tx.Find(group, c.Param("group_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, group))
}
// Update changes a Group in the DB. This function is mapped to
// the path PUT /groups/{group_id}
func (v GroupsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Group
  group := &models.Group{}

  if err := tx.Find(group, c.Param("group_id")); err != nil {
    return c.Error(404, err)
  }

  // Bind Group to the html form elements
  if err := c.Bind(group); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(group)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the edit.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, group))
  }

  // If there are no errors set a success message
  c.Flash().Add("success", T.Translate(c, "group.updated.success"))
  // and redirect to the groups index page
  return c.Render(200, r.Auto(c, group))
}

// Destroy deletes a Group from the DB. This function is mapped
// to the path DELETE /groups/{group_id}
func (v GroupsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Group
  group := &models.Group{}

  // To find the Group the parameter group_id is used.
  if err := tx.Find(group, c.Param("group_id")); err != nil {
    return c.Error(404, err)
  }

  if err := tx.Destroy(group); err != nil {
    return err
  }

  // If there are no errors set a flash message
  c.Flash().Add("success", T.Translate(c, "group.destroyed.success"))
  // Redirect to the groups index page
  return c.Render(200, r.Auto(c, group))
}
