package actions

import (

  "fmt"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "secret_santa/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (UserWish)
// DB Table: Plural (user_wishes)
// Resource: Plural (UserWishes)
// Path: Plural (/user_wishes)
// View Template Folder: Plural (/templates/user_wishes/)

// UserWishesResource is the resource for the UserWish model
type UserWishesResource struct{
  buffalo.Resource
}

// List gets all UserWishes. This function is mapped to the path
// GET /user_wishes
func (v UserWishesResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  userWishes := &models.UserWishes{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all UserWishes from the DB
  if err := q.All(userWishes); err != nil {
    return err
  }

  // Add the paginator to the context so it can be used in the template.
  c.Set("pagination", q.Paginator)

  return c.Render(200, r.Auto(c, userWishes))
}

// Show gets the data for one UserWish. This function is mapped to
// the path GET /user_wishes/{user_wish_id}
func (v UserWishesResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty UserWish
  userWish := &models.UserWish{}

  // To find the UserWish the parameter user_wish_id is used.
  if err := tx.Find(userWish, c.Param("user_wish_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, userWish))
}

// New renders the form for creating a new UserWish.
// This function is mapped to the path GET /user_wishes/new
func (v UserWishesResource) New(c buffalo.Context) error {
  return c.Render(200, r.Auto(c, &models.UserWish{}))
}
// Create adds a UserWish to the DB. This function is mapped to the
// path POST /user_wishes
func (v UserWishesResource) Create(c buffalo.Context) error {
  // Allocate an empty UserWish
  userWish := &models.UserWish{}

  // Bind userWish to the html form elements
  if err := c.Bind(userWish); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(userWish)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the new.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, userWish))
  }

  // If there are no errors set a success message
  c.Flash().Add("success", T.Translate(c, "userWish.created.success"))
  // and redirect to the user_wishes index page
  return c.Render(201, r.Auto(c, userWish))
}

// Edit renders a edit form for a UserWish. This function is
// mapped to the path GET /user_wishes/{user_wish_id}/edit
func (v UserWishesResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty UserWish
  userWish := &models.UserWish{}

  if err := tx.Find(userWish, c.Param("user_wish_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, userWish))
}
// Update changes a UserWish in the DB. This function is mapped to
// the path PUT /user_wishes/{user_wish_id}
func (v UserWishesResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty UserWish
  userWish := &models.UserWish{}

  if err := tx.Find(userWish, c.Param("user_wish_id")); err != nil {
    return c.Error(404, err)
  }

  // Bind UserWish to the html form elements
  if err := c.Bind(userWish); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(userWish)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the edit.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, userWish))
  }

  // If there are no errors set a success message
  c.Flash().Add("success", T.Translate(c, "userWish.updated.success"))
  // and redirect to the user_wishes index page
  return c.Render(200, r.Auto(c, userWish))
}

// Destroy deletes a UserWish from the DB. This function is mapped
// to the path DELETE /user_wishes/{user_wish_id}
func (v UserWishesResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty UserWish
  userWish := &models.UserWish{}

  // To find the UserWish the parameter user_wish_id is used.
  if err := tx.Find(userWish, c.Param("user_wish_id")); err != nil {
    return c.Error(404, err)
  }

  if err := tx.Destroy(userWish); err != nil {
    return err
  }

  // If there are no errors set a flash message
  c.Flash().Add("success", T.Translate(c, "userWish.destroyed.success"))
  // Redirect to the user_wishes index page
  return c.Render(200, r.Auto(c, userWish))
}
